example.property: I am the prod.

server:
  port: 10002

#服务发现客户端
eureka:
  instance:
    #向Eureka注册时，是否使用IP地址+端口号作为服务实例的唯一标识。推荐设置为true
    prefer-ip-address: true

  client:
    #是否将自身的实例信息注册到Eureka服务端
    register-with-eureka: true
    #是否拉取并缓存其他服务注册表副本到本地
    fetch-registry: true
    #注册到哪个Eureka服务实例
    service-url:
      defaultZone: http://localhost:8761/eureka/

#数据源的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prodDB?useSSL=true&characterEncoding=utf8
    username: root
    password: root
    tomcat:
      validation-query: "select 1"
      max-active: 20
      max-wait: 100000
      test-while-idle: true
      min-idle: 5
      initial-size: 5
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect