server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/,classpath:config/licenseservice

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/spring-cloud-study/spring-cloud-study-config-repo
#          search-paths: licenseservice
#          username: 3257722804@qq.com
#          password: a12345678